export const cities = {
  EG: [
    { enName: 'Luxor', arName: 'الأقصر' },
    { enName: 'Alexandria', arName: 'الاسكندرية' },
    { enName: 'Ash-Sharqiyah', arName: 'الشرقية' },
    { enName: 'Assiut', arName: 'اسيوط' },
    { enName: 'Behira', arName: 'البحيرة' },
    { enName: 'Cairo', arName: 'القاهرة' },
    { enName: 'Damietta', arName: 'دمياط' },
    { enName: 'Kafr El-Sheikh', arName: 'كفر الشيخ' },
    { enName: 'Menoufia', arName: 'المنوفية' },
    { enName: 'Minya', arName: 'المنيا' },
    { enName: 'Port Said', arName: 'بورسعيد' },
    { enName: 'Qalubiya', arName: 'القليوبية' },
    { enName: 'Ismailiya', arName: 'الاسماعيلية' },
    { enName: 'Aswan', arName: 'اسوان' },
    { enName: 'Bani Suwayf', arName: 'بني سويف' },
    { enName: 'Dakahlia', arName: 'الدقهلية' },
    { enName: 'Faiyum', arName: 'الفيوم' },
    { enName: 'Gharbiya', arName: 'الغربية' },
    { enName: 'Gizah', arName: 'الجيزة' },
    { enName: 'Red Sea', arName: 'البحر الأحمر' },
    { enName: 'Qena', arName: 'قنا' },
    { enName: 'South Sinai', arName: 'جنوب سيناء' },
    { enName: 'North Sinai', arName: ' شمال سيناء' },
    { enName: 'Suez', arName: ' السويس' },
    { enName: 'Suhaj', arName: ' سوهاج' },
    { enName: 'Wadi al-Jadid', arName: ' الوادي الجديد' },
    { enName: 'Matrouh', arName: ' مطروح' }
  ],

  SA: [
    { enName: 'Abhā', arName: 'ابها' },
    { enName: 'Abqaīq', arName: 'بقيق' },
    { enName: 'Abqaīq', arName: 'بقيق' },
    { enName: 'AbūArīsh', arName: 'ابو عريش' },
    { enName: 'Ad-Dammām', arName: ' الدمام ' },
    { enName: 'Ad-Dawādmī', arName: ' الدوادمي ' },
    { enName: 'Ad-Dilam', arName: ' الدلم ' },
    { enName: 'Ad-Ad-Diriyah', arName: ' الدرعية ' },
    { enName: 'Ad-Aḥad al-Masāriḥah', arName: ' احد المسارحة ' },
    { enName: 'Aḥad Rāfidah', arName: 'احد رفيدة ' },
    { enName: 'Al-Awāmiyah', arName: 'العوامية ' },
    { enName: 'Al-Badāia', arName: 'البدائع ' },
    { enName: 'Al-Bāḥah', arName: 'الباحة ' },
    { enName: 'Al-Bukayriyah', arName: 'البكيرية ' },
    { enName: 'Al-Ḥawiyah', arName: 'الحويه ' },
    { enName: 'Al-Al-Hufūf', arName: 'الهفوف و المبرز ' },
    { enName: 'Al-Jubaīl', arName: 'الجبيل ' },
    { enName: 'Al-Jumūm', arName: 'الجموم ' },
    { enName: 'Al-Khafjī', arName: 'الخفجي ' },
    { enName: 'Al-Kharj', arName: 'الخرج ' },
    { enName: 'Al-Khubar', arName: 'الخبر ' },
    { enName: 'Al-Khubar', arName: 'الخبر ' },
    { enName: 'Al-Khurmah', arName: 'الخرمة ' },
    { enName: 'Al-Madīnah', arName: 'المدينة ' },
    { enName: 'Al-Majmaah', arName: 'المجمعة ' },
    { enName: 'Al-Makhwāh', arName: 'المخواة ' },
    { enName: 'Al-Midhnab', arName: 'المذنب ' },
    { enName: 'Al-MidAl-Muzāḥimiyah', arName: 'المزاحمية ' },
    { enName: 'Al-Qaīṣūmah', arName: 'القيصومة ' },
    { enName: 'Al-Qaṭīf', arName: 'القطيف ' },
    { enName: 'Al-Qudaīḥ', arName: 'القديح ' },
    { enName: 'Al-Qunfudhah', arName: 'القنفذة ' },
    { enName: 'Al-Qurayyāt', arName: 'القريات ' },
    { enName: 'Al-Qūwayiyah', arName: 'القويعية ' },
    { enName: 'Al-Qūz', arName: 'القوز ' },
    { enName: 'Al-Ulā', arName: 'العلا ' },
    { enName: 'Al-Ulāyah', arName: 'العلاية ' },
    { enName: 'Al-Al-Uyūn', arName: 'العيون ' },
    { enName: 'Al-Wajh', arName: 'الوجه ' },
    { enName: 'Ank', arName: 'عنك ' },
    { enName: 'An-Nimāṣ', arName: 'النماص ' },
    { enName: 'An-Nuayriyah', arName: 'النعيرية ' },
    { enName: 'Arar', arName: 'عرعر ' },
    { enName: 'Ar-Rass', arName: 'الرس ' },
    { enName: 'Ar-Riyāḍ', arName: 'الرياض ' },
    { enName: 'As-Sulayyil', arName: 'السليل ' },
    { enName: 'Ath-Thuqbah', arName: 'الثقبة ' },
    { enName: 'Aṭ-Ṭaif', arName: 'الطائف ' },
    { enName: 'Aṭ-Ṭaraf', arName: 'الطرف ' },
    { enName: 'Aẓ-Ẓahrān', arName: 'الظهران ' },
    { enName: 'Az-Zulfī', arName: 'الزلفي ' },
    { enName: 'Badr', arName: 'بدر' },
    { enName: 'Bahrah', arName: 'بحرة' },
    { enName: 'Baljurashī', arName: 'بلجرشي' },
    { enName: 'Bīsh', arName: 'بيش' },
    { enName: 'Bīsh', arName: 'بيشة' },
    { enName: 'Buraydah', arName: 'بريدة' },
    { enName: 'Ḍamad', arName: 'ضمد' },
    { enName: 'Ḍubā', arName: ' ضباء' },
    { enName: 'Dūmat al-Jandal', arName: 'دومة الجندل' },
    { enName: 'Ḥafar al-Bāṭin', arName: 'حفر الباطنل' },
    { enName: 'Ḥāil', arName: 'حائل' },
    { enName: 'Ḥaql', arName: 'حقل' },
    { enName: 'Ḥawṭah Banī Tamīm', arName: 'حوطة بني تميم' },
    { enName: 'Jiddah', arName: 'جدة' },
    { enName: 'Jīzān', arName: 'جيزان' },
    { enName: 'Khamīs Mushaīṭ', arName: 'خميس مشيط' },
    { enName: 'Laylā', arName: 'ليلى' },
    { enName: 'Makkah', arName: 'مكة' },
    { enName: 'Muḥāyil', arName: 'محائل' },
    { enName: 'Najrān', arName: 'نجران' },
    { enName: 'Rābigh', arName: 'رابغ' },
    { enName: 'Rafḥā', arName: 'رفحاء' },
    { enName: 'Raḥīmah', arName: 'رحيمة' },
    { enName: 'Ranyah', arName: 'رنية' },
    { enName: 'Ranyah', arName: 'رنية' },
    { enName: 'Rimāḥ', arName: 'رماح' },
    { enName: 'Ṣabyā', arName: 'صبيا' },
    { enName: 'Ṣafwah', arName: 'صفوى' },
    { enName: 'Saīhāt', arName: 'سيهات' },
    { enName: 'Sakākā', arName: 'سكاكا' },
    { enName: 'Ṣāmiṭah', arName: 'صامطة' },
    { enName: 'Shaqrā', arName: 'شقراء' },
    { enName: 'Sharūrah', arName: 'شرورة' },
    { enName: 'Tabūk', arName: 'تبوك' },
    { enName: 'Tārūt', arName: 'تاروت' },
    { enName: 'Taymā', arName: 'تيماء' },
    { enName: 'Ṭubarjal', arName: 'طبرجل' },
    { enName: 'Ṭuraīf', arName: 'طريف' },
    { enName: 'Turubah', arName: 'تربة' },
    { enName: 'Umluj', arName: 'أملج' },
    { enName: 'Unaīzah', arName: 'عنيزة' },
    { enName: 'Wādī ad-Dawāsir', arName: 'وادي الدواسر' },
    { enName: 'Yanbu al-Baḥr', arName: ' ينبع البحر' },
    { enName: ' Ẓahrān al-Janūb-Baḥr', arName: 'ظهران الجنوب' }
  ],

  KW: [
    { enName: 'Al-Aḥmadī', arName: 'الاحمدي' },
    { enName: 'Al-Āṣimah', arName: 'العاصمة' },
    { enName: 'Al-Farwānīyah', arName: 'الفروانية' },
    { enName: 'Al-Jahrā', arName: 'الجهراء' },
    { enName: 'Ḥawallī', arName: 'حولي' },
    { enName: 'Mubarāk al-Kabīr', arName: 'مبارك الكبير' }
  ],

  AE: [
    { enName: 'Abū Ẓaby', arName: 'ابو ظبى' },
    { enName: 'Ad-Dhaīd', arName: 'الذيد' },
    { enName: 'Ajmān', arName: 'عجمان' },
    { enName: 'Al-Ḥamriyah', arName: 'الحمریه' },
    { enName: 'Al-Madām', arName: 'المدام' },
    { enName: 'Al-Manāmah', arName: 'المنامة' },
    { enName: 'Al-Ayn', arName: 'العين' },
    { enName: 'Al-Baṭāeḥ', arName: 'البطائح' },
    { enName: 'Al-Fujayrah', arName: 'الفجيرة' },
    { enName: 'Dubayy', arName: 'دبى' },
    { enName: 'Ḥatā', arName: 'حتا' },
    { enName: 'Kalbā', arName: 'كلباء' },
    { enName: 'Ash-Shāriqah', arName: 'الشارقة' },
    { enName: 'Dibā al-Fujayrah', arName: 'دبا الفجيرة' },
    { enName: 'Dibā al-Ḥiṣn', arName: 'دبا الحصن' },
    { enName: 'Khawr Fakān', arName: 'خور فكان' },
    { enName: 'Maṣfūt', arName: 'مصفوت' },
    { enName: 'Mileīḥah', arName: 'مليحة' },
    { enName: 'Rās al-Khaymah', arName: 'رأس الخيمة' },
    { enName: 'Umm al-Qaywayn', arName: 'ام القيوين' }
  ]
};
